AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Authorizer for my apis
Resources:
  AuthKeyAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://szachista-authorizer/6136fa996807db8fc3e3ea4aa2bafb3a
      Handler: app.handler
      Runtime: nodejs10.x
      Description: Authorizer for my apis
      MemorySize: 512
      Timeout: 10
