AWSTemplateFormatVersion: '2010-09-09'
Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
Resources:
  AuthKeyApi:
    Properties:
      CodeUri: s3://szachista-connection-auth-keys-api/5c700e2d8a41b32ea0867fd6427cc6a4
      Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
      Events:
        create:
          Properties:
            Method: POST
            Path: /auth-key
          Type: Api
        rest:
          Properties:
            Method: ANY
            Path: /auth-key/{id}
          Type: Api
      Handler: app.handler
      MemorySize: 512
      Policies:
      - Statement:
        - Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/connection_auth_keys
        Version: '2012-10-17'
      Runtime: nodejs10.x
      Timeout: 10
    Type: AWS::Serverless::Function
  myHelloTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: key
        AttributeType: S
      KeySchema:
      - AttributeName: key
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: connection_auth_keys
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
